#!/usr/bin/env python3

import pigpio
import time
import argparse
import sys

# --------- pin numbers
# --- usb
usb_pin = 4
# --- power
power_pin = 18


# --------- hardware setup
pi = pigpio.pi()
pi.set_mode(usb_pin, pigpio.OUTPUT)


# --------- arguments
parser = argparse.ArgumentParser()
# --- usb switch
usb_arghelp = 'usb on/off, valid value: "on" or "off"'
parser.add_argument('-u', '--usb', type=str, help=usb_arghelp)
# --- power switch
power_arghelp = 'power toggle or long press, valid value: "toggle", "longpress"'
parser.add_argument('-p', '--power', type=str, help=power_arghelp)
# --- parse args
args = parser.parse_args()


# --------- app logic
if len(sys.argv) == 1:
    parser.print_help()
else:
    if args.usb:
        if args.usb == 'on':
            pi.write(usb_pin, True)
        elif args.usb == 'off':
            pi.write(usb_pin, False)
        else:
            print(usb_arghelp)
    if args.power:
        if args.power == 'toggle':
            pi.write(power_pin, True)
            time.sleep(0.2)
            pi.write(power_pin, False)
        elif args.power == 'longpress':
            pi.write(power_pin, True)
            time.sleep(5)
            pi.write(power_pin, False)
        else:
            print(power_arghelp)


